//! The document a yell sends: `openappa.yell.v1`.
//!
//! This module holds no I/O and reaches nothing. It takes a message, a build identity and an
//! already-classified [`super::Diagnostic`], and turns them into bytes. Everything that decides
//! *what* may appear lives in [`super::strip`] and [`super::policy`]; everything that decides
//! *whether to send* lives in the CLI and the tool handler. Here the only questions are shape
//! and size.
//!
//! Size is a two-sided bound. [`MAX_GZIPPED_BYTES`] and [`MAX_PLAIN_BYTES`] sit under the caps
//! `receiver/appa-yell` enforces, by the width of a request's headers — which is what the
//! receiver measures and this module does not. A report that does not fit is not truncated
//! here: [`finalize`](Report::finalize) reports the measurement and the caller asks the runtime
//! for a smaller export, which renumbers from its own start.

use std::path::{Path, PathBuf};

use serde::Serialize;

use super::diagnostic::Policy;
use super::strip::Drift;
use super::tokens::Mode;
use super::{Diagnostic, OmittedReason, Projection};
use appa_runtime_api::AdapterName;

/// The one schema this client writes. A receiver that does not know it refuses the document,
/// and a caller that reads a document back checks this before believing any of it.
pub(crate) const SCHEMA: &str = "openappa.yell.v1";

/// The largest body this client puts on the wire, gzipped, and the largest document behind it.
///
/// Both sit under `receiver/appa-yell`'s own caps by the width of a request's headers, and the
/// plain cap is the one that has to agree: a receiver decompresses before it can validate, so
/// a document this client is willing to send and that receiver is not willing to hold would
/// fail every attempt forever. The facts alone are bounded well below it
/// ([`super::diagnostic::MAX_FACT_BYTES`]), and a trajectory large enough to pass it is
/// rebuilt smaller by the size loop rather than refused.
pub(crate) const MAX_GZIPPED_BYTES: usize = 28 * 1024 * 1024;
pub(crate) const MAX_PLAIN_BYTES: usize = 32 * 1024 * 1024;

/// The longest message a person or an agent can send. Longer is a paste of something else.
pub(crate) const MAX_MESSAGE_BYTES: usize = 64 * 1024;

/// What someone wants to say. The only free-form field in the document, and the only one whose
/// content nothing in this crate inspects — so it is bounded and validated once, here, rather
/// than trusted at each place it passes through.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(crate) struct YellMessage(String);

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub(crate) enum MessageRefusal {
    #[error("a yell needs a message")]
    Empty,
    #[error("a message is at most {MAX_MESSAGE_BYTES} bytes, and this one is {bytes}")]
    TooLong { bytes: usize },
}

impl YellMessage {
    pub(crate) fn new(raw: &str) -> Result<Self, MessageRefusal> {
        let trimmed = raw.trim();
        match trimmed.len() {
            0 => Err(MessageRefusal::Empty),
            bytes if bytes > MAX_MESSAGE_BYTES => Err(MessageRefusal::TooLong { bytes }),
            _ => Ok(Self(trimmed.to_owned())),
        }
    }
}

/// A report's own name, generated by the client. The receiver stores one object per id, so a
/// resend of the same bytes lands on the same object rather than a second report.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(crate) struct ReportId(String);

impl ReportId {
    pub(crate) fn generate() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }
}

/// Who yelled. A person and an agent are read differently: an agent's message is the model's
/// account of what APPA did to it, and a person's is a person's.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum Author {
    Cli,
    Agent,
}

#[derive(Debug, Clone, Copy, Serialize)]
pub(crate) struct Origin {
    pub(crate) kind: Author,
    /// True when the deployment's own names were replaced by report-local tokens. The reader
    /// needs this to know whether `tool-1` is a token or a tool someone named `tool-1`.
    pseudonymized: bool,
}

impl Origin {
    pub(crate) fn new(kind: Author, mode: Mode) -> Self {
        Self {
            kind,
            pseudonymized: mode == Mode::Pseudonymized,
        }
    }
}

/// Which build yelled. Enough to check out the source that produced the behaviour, and nothing
/// about the machine it ran on: a local build names no path, because a path names a person.
#[derive(Debug, Clone, Copy, Serialize)]
pub(crate) struct Build {
    version: &'static str,
    source: BuildSource,
    platform: Platform,
}

/// Tagged by a `kind` field rather than externally, which would spell a commit
/// `{"commit": {"commit": "…"}}`.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub(crate) enum BuildSource {
    Release { reference: &'static str },
    Commit { commit: &'static str },
    Local,
}

#[derive(Debug, Clone, Copy, Serialize)]
pub(crate) struct Platform {
    os: &'static str,
    arch: &'static str,
}

impl Build {
    /// This binary, as its build script stamped it.
    pub(crate) fn compiled() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION"),
            source: match (option_env!("APPA_RELEASE_REF"), option_env!("APPA_BUILD_COMMIT")) {
                (Some(reference), _) => BuildSource::Release { reference },
                (None, Some(commit)) => BuildSource::Commit { commit },
                (None, None) => BuildSource::Local,
            },
            platform: Platform {
                os: std::env::consts::OS,
                arch: std::env::consts::ARCH,
            },
        }
    }
}

/// The runtime the report is about, or the reason there is none to describe.
///
/// A person can yell with no runtime running, and that report is worth having — "it is not
/// running" is a common thing to be angry about. The refusal carries a class and never the
/// error text, which on a connect failure names a socket path.
#[derive(Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum RuntimeSection {
    Serving {
        /// The harness whose hooks this runtime serves.
        harness: Harness,
        #[serde(skip_serializing_if = "Option::is_none")]
        hostname: Option<String>,
        /// The rules in force, stripped against [`super::policy`]. `None` when the runtime
        /// could not resolve one, which is itself the interesting case.
        policy: Option<Policy>,
    },
    Unreachable {
        class: UnreachableClass,
    },
}

/// The harness a report is about, in the schema's own vocabulary: a served host by its
/// adapter name, an embedding host by the name it files its reports under.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Harness {
    ClaudeCode,
    Codex,
    Kagent,
    Amp,
    Embedded(HarnessName),
}

/// The name an embedding host files its reports under: spelled as a package name is,
/// lowercase letters, digits and hyphens, at most 64 bytes long, and never an adapter
/// name, so a receipt or trace tells an embedding host from a served deployment.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HarnessName(String);

#[derive(Debug, thiserror::Error)]
pub enum HarnessNameError {
    #[error(transparent)]
    Malformed(#[from] appa_package::NameError),
    #[error("`{name}` is longer than {max} bytes")]
    TooLong { name: String, max: usize },
    #[error("`{0}` is an adapter name, which an embedding host cannot report as")]
    Reserved(String),
}

impl HarnessName {
    pub const MAX_LEN: usize = 64;

    pub fn parse(text: &str) -> Result<Self, HarnessNameError> {
        if text.len() > Self::MAX_LEN {
            return Err(HarnessNameError::TooLong {
                name: text.to_owned(),
                max: Self::MAX_LEN,
            });
        }
        appa_package::PackageName::parse(text)?;
        let reserved = AdapterName::ALL
            .iter()
            .chain(std::iter::once(&AdapterName::Embedded))
            .any(|adapter| adapter.as_str() == text);
        if reserved {
            return Err(HarnessNameError::Reserved(text.to_owned()));
        }
        Ok(Self(text.to_owned()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Harness {
    /// The harness a served runtime reports about. An embedding host is no served
    /// runtime: it reports through [`super::embedded`], naming itself there.
    pub(crate) fn served(adapter: AdapterName) -> Self {
        match adapter {
            AdapterName::ClaudeCode => Harness::ClaudeCode,
            AdapterName::Codex => Harness::Codex,
            AdapterName::Kagent => Harness::Kagent,
            AdapterName::Amp => Harness::Amp,
            AdapterName::Embedded => unreachable!("a served runtime is started with a served adapter"),
        }
    }

    fn as_str(&self) -> &str {
        match self {
            Harness::ClaudeCode => "claude-code",
            Harness::Codex => "codex",
            Harness::Kagent => "kagent",
            Harness::Amp => "amp",
            Harness::Embedded(name) => name.as_str(),
        }
    }
}

impl Serialize for Harness {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

/// Why the CLI has nothing to say about a runtime. Each is a state a reader can act on.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum UnreachableClass {
    /// Nothing is listening: no runtime for this configuration is up.
    NotListening,
    /// Something is listening but did not answer in time.
    Timeout,
    /// It answered and would not build a report: an older build that does not serve one, or a
    /// trajectory too large to send even trimmed.
    Refused { status: u16 },
    /// It answered with something that is not this schema, so it is not a runtime of this
    /// build and nothing it said was used.
    NotARuntime,
    /// The runtime was named somewhere other than this machine. Nothing was sent there: the
    /// message had not yet been approved for leaving at all.
    NotLoopback,
}

/// What a caller asks the runtime to build. Everything the document does not derive from the
/// runtime's own state.
#[derive(Debug, Clone)]
pub(crate) struct ReportRequest {
    pub(crate) message: YellMessage,
    pub(crate) author: Author,
    pub(crate) mode: Mode,
    pub(crate) selection: super::Selection,
    pub(crate) harness: Harness,
    pub(crate) hostname: Option<String>,
}

/// The document itself, in the order a reader reads it.
#[derive(Debug, Serialize)]
pub(crate) struct Report {
    schema: &'static str,
    report_id: ReportId,
    created_at: String,
    origin: Origin,
    message: YellMessage,
    build: Build,
    runtime: RuntimeSection,
    trajectory: Diagnostic,
    /// Where the classification inventory has drifted from the engine, for everything above.
    unclassified: Vec<Drift>,
}

impl Report {
    /// A report about a runtime that answered.
    pub(crate) fn serving(
        report_id: ReportId,
        origin: Origin,
        message: YellMessage,
        harness: Harness,
        projection: Projection,
    ) -> Self {
        Self::new(
            report_id,
            origin,
            message,
            RuntimeSection::Serving {
                harness,
                hostname: None,
                policy: projection.policy,
            },
            projection.trajectory,
            projection.unclassified,
        )
    }

    pub(crate) fn with_hostname(mut self, hostname: Option<String>) -> Self {
        if let RuntimeSection::Serving { hostname: target, .. } = &mut self.runtime {
            *target = hostname;
        }
        self
    }

    /// A report about a runtime that did not. Worth sending: "it is not running" is a common
    /// thing to be angry about, and the build and the message still say who and what.
    pub(crate) fn unreachable(
        report_id: ReportId,
        origin: Origin,
        message: YellMessage,
        class: UnreachableClass,
    ) -> Self {
        Self::new(
            report_id,
            origin,
            message,
            RuntimeSection::Unreachable { class },
            Diagnostic::Omitted {
                omitted_reason: OmittedReason::RuntimeUnavailable,
            },
            Vec::new(),
        )
    }

    fn new(
        report_id: ReportId,
        origin: Origin,
        message: YellMessage,
        runtime: RuntimeSection,
        trajectory: Diagnostic,
        unclassified: Vec<Drift>,
    ) -> Self {
        Self {
            schema: SCHEMA,
            report_id,
            created_at: super::diagnostic::rfc3339(std::time::SystemTime::now()),
            origin,
            message,
            build: Build::compiled(),
            runtime,
            trajectory,
            unclassified,
        }
    }

    /// The bytes to keep and the bytes to send, or the measurement that refused them.
    ///
    /// The file on disk is the plain JSON, so a person reads what they approved; the wire
    /// carries the same bytes gzipped, and the signature covers the plain ones. Nothing here
    /// drops content: an oversized report comes back as a measurement, and the caller rebuilds
    /// a shorter export rather than cutting entries out of this finished document.
    pub(crate) fn finalize(&self) -> Result<Finished, Oversize> {
        // A report is plain data — strings, numbers, and `Value`s serde itself produced — so
        // the only way this fails is a bug in a `Serialize` impl in this module.
        Finished::of(serde_json::to_vec(self).expect("a report is plain data and serializes"))
    }
}

/// One report, in both the forms it is used in. Built together so they cannot disagree.
#[derive(Debug)]
pub(crate) struct Finished {
    pub(crate) plain: Vec<u8>,
    pub(crate) gzipped: Vec<u8>,
}

impl Finished {
    /// A document another process finished, measured here before it is kept or sent.
    pub(crate) fn of(plain: Vec<u8>) -> Result<Self, Oversize> {
        if plain.len() > MAX_PLAIN_BYTES {
            return Err(Oversize::Plain { bytes: plain.len() });
        }
        let gzipped = gzip(&plain);
        match gzipped.len() > MAX_GZIPPED_BYTES {
            true => Err(Oversize::Gzipped { bytes: gzipped.len() }),
            false => Ok(Self { plain, gzipped }),
        }
    }
}

/// How far over a limit a report came out. The caller halves what it asks the runtime for and
/// builds again; it never edits these bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub(crate) enum Oversize {
    #[error("the report is {bytes} bytes, over the {MAX_PLAIN_BYTES}-byte limit")]
    Plain { bytes: usize },
    #[error("the report is {bytes} bytes gzipped, over the {MAX_GZIPPED_BYTES}-byte limit")]
    Gzipped { bytes: usize },
}

fn gzip(plain: &[u8]) -> Vec<u8> {
    use std::io::Write;

    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
    encoder.write_all(plain).expect("a `Vec` writer does not fail");
    encoder.finish().expect("a `Vec` writer does not fail")
}

/// Where a finished report waits while its author decides.
#[derive(Debug)]
pub(crate) struct Written {
    pub(crate) path: PathBuf,
    pub(crate) finished: Finished,
}

#[derive(Debug, thiserror::Error)]
#[error("the report could not be written under {}: {source}", directory.display())]
pub(crate) struct WriteError {
    directory: PathBuf,
    source: std::io::Error,
}

/// Write the report where its author can read it before answering, and keep it afterwards
/// either way.
///
/// The document holds no bodies and no arguments, but it does hold a deployment's tool and
/// authority names, so it is not world-readable while it sits in a shared temporary directory:
/// a fresh directory at 0700 with the file at 0600, created exclusively so a name that already
/// exists is never followed. On Unix that is the whole guarantee. On Windows the protection is
/// the per-user temporary directory this writes into, and nothing here adds to it.
///
/// The directory is only made permanent once the file is written and flushed. A failure part
/// way through takes the directory and the partial file with it, rather than leaving a person
/// a half-document that reads like a whole one.
pub(crate) fn write(finished: Finished, directory: &Path) -> Result<Written, WriteError> {
    let refuse = |source| WriteError {
        directory: directory.to_path_buf(),
        source,
    };
    let mut builder = tempfile::Builder::new();
    builder.prefix("appa-yell-");
    // Mode bits are the whole guarantee on Unix. Windows has none to set here, and
    // `Permissions` cannot be built from nothing, so the per-user temporary
    // directory is the protection there.
    #[cfg(unix)]
    builder.permissions(std::os::unix::fs::PermissionsExt::from_mode(0o700));
    let held = builder.tempdir_in(directory).map_err(refuse)?;
    let path = held.path().join("report.json");
    let mut file = std::fs::OpenOptions::new();
    file.write(true).create_new(true);
    #[cfg(unix)]
    std::os::unix::fs::OpenOptionsExt::mode(&mut file, 0o600);
    let mut handle = file.open(&path).map_err(refuse)?;
    std::io::Write::write_all(&mut handle, &finished.plain).map_err(refuse)?;
    handle.sync_all().map_err(refuse)?;
    Ok(Written {
        path: held.keep().join("report.json"),
        finished,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::yell::OmittedReason;

    fn report(message: &str) -> Report {
        Report::unreachable(
            ReportId::generate(),
            Origin::new(Author::Cli, Mode::Baseline),
            YellMessage::new(message).expect("the fixture message is valid"),
            UnreachableClass::NotListening,
        )
    }

    #[test]
    fn a_message_is_bounded_and_never_empty() {
        assert_eq!(YellMessage::new("  \n "), Err(MessageRefusal::Empty));
        assert_eq!(YellMessage::new(""), Err(MessageRefusal::Empty));
        let long = "x".repeat(MAX_MESSAGE_BYTES + 1);
        assert_eq!(
            YellMessage::new(&long),
            Err(MessageRefusal::TooLong {
                bytes: MAX_MESSAGE_BYTES + 1
            })
        );
        assert!(YellMessage::new(&"x".repeat(MAX_MESSAGE_BYTES)).is_ok());
    }

    /// Multi-line input is one message: a person pasting a session's tail means all of it.
    #[test]
    fn a_message_keeps_its_lines_and_loses_its_edges() {
        let message = YellMessage::new("\n first\nsecond \n\n").expect("the message is valid");
        assert_eq!(message.0, "first\nsecond");
    }

    #[test]
    fn a_finished_report_reads_back_as_the_schema_it_claims() {
        let report = report("the hook blocked a read of my own file");
        let finished = report.finalize().expect("a metadata-only report fits");

        let parsed: serde_json::Value = serde_json::from_slice(&finished.plain).expect("the report is JSON");
        assert_eq!(parsed["schema"], SCHEMA);
        assert_eq!(
            parsed["report_id"].as_str().map(str::len),
            Some(36),
            "the report names itself with a v4 UUID"
        );
        assert_eq!(parsed["origin"]["kind"], "cli");
        assert_eq!(parsed["origin"]["pseudonymized"], false);
        assert_eq!(parsed["runtime"]["unreachable"]["class"], "not_listening");
        assert_eq!(parsed["trajectory"]["omitted_reason"], "runtime_unavailable");
        assert!(parsed["created_at"].as_str().is_some_and(|at| at.ends_with('Z')));
    }

    /// The wire body and the file are the same document, so a person who reads the file has
    /// read what was sent.
    #[test]
    fn the_body_on_the_wire_gunzips_to_the_file() {
        let finished = report("something").finalize().expect("the report fits");
        let mut plain = Vec::new();
        std::io::Read::read_to_end(
            &mut flate2::read::GzDecoder::new(finished.gzipped.as_slice()),
            &mut plain,
        )
        .expect("the body is gzip");
        assert_eq!(plain, finished.plain);
    }

    #[test]
    fn pseudonymization_and_the_harness_are_stated_in_the_document() {
        let report = Report::serving(
            ReportId::generate(),
            Origin::new(Author::Cli, Mode::Pseudonymized),
            YellMessage::new("x").expect("valid"),
            Harness::served(AdapterName::ClaudeCode),
            Projection::rules_only(None, Mode::Pseudonymized, OmittedReason::NoRecentTrajectory),
        );
        let finished = report.finalize().expect("the report fits");
        let parsed: serde_json::Value = serde_json::from_slice(&finished.plain).expect("the report is JSON");
        assert_eq!(parsed["origin"]["pseudonymized"], true);
        assert_eq!(parsed["runtime"]["serving"]["harness"], "claude-code");
        assert_eq!(parsed["trajectory"]["omitted_reason"], "no_recent_trajectory");
    }

    #[test]
    fn the_written_report_is_the_author_s_alone() {
        let directory = tempfile::tempdir().expect("a temp dir is creatable");
        let finished = report("kept either way").finalize().expect("the report fits");
        let written = write(finished, directory.path()).expect("the report is written");

        assert_eq!(
            std::fs::read(&written.path).expect("the file is readable"),
            written.finished.plain
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = |path: &Path| std::fs::metadata(path).expect("the path exists").permissions().mode() & 0o777;
            assert_eq!(mode(&written.path), 0o600);
            assert_eq!(mode(written.path.parent().expect("the file has a directory")), 0o700);
        }
    }

    /// Two yells in one directory do not collide, and neither follows a name already there.
    #[test]
    fn each_report_gets_its_own_directory() {
        let directory = tempfile::tempdir().expect("a temp dir is creatable");
        let first = write(report("one").finalize().expect("fits"), directory.path()).expect("written");
        let second = write(report("two").finalize().expect("fits"), directory.path()).expect("written");
        assert_ne!(first.path, second.path);
    }
}
